[versions]

kotlin = "2.2.21"

# Spring
spring-boot = "3.5.8"
spring-dependencyManagement = "1.1.7"

gorylenko-gitProperties = "2.5.4"

[libraries]

gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-spring-kotlin = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
gradlePlugin-spring-boot = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
gradlePlugin-spring-dependencyManagement = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "spring-dependencyManagement" }
gradlePlugin-gitProperties = { module = "com.gorylenko.gradle-git-properties:gradle-git-properties", version.ref = "gorylenko-gitProperties" }
